import { Employee, UserRole, EmploymentStatus } from '../types';

interface RawStaff {
  sl: number;
  eid: string;
  name: string;
  desig: string;
  dept: string;
  status: string;
  mobile?: string;
  pMail?: string;
  offMail?: string;
  nid?: string;
  dob?: string;
  addr?: string;
  edu?: string;
  profEdu?: string;
  cert?: string;
  father?: string;
  mother?: string;
  gender?: string;
  rel?: string;
  nature: string;
  locCat?: string;
  loc?: string;
  doj: string;
  doc?: string;
  dos?: string;
  reason?: string;
  emg?: string;
  remarks?: string;
  daysPerWeek?: number;
  inTime?: string;
  outTime?: string;
  dailyHours?: number;
}

const rawList: RawStaff[] = [
  { sl: 1, eid: "1001", name: "Forhad Hossain", desig: "Founder & ED", dept: "Executive Management", status: "Active", mobile: "01819-291567", offMail: "helpstreetchildren4survive@gmail.com", edu: "MBA", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2015", daysPerWeek: 6 },
  { sl: 2, eid: "1002", name: "Murshida Akhter Kanta", desig: "Director - Admin & Finance", dept: "Admin & Finance", status: "Active", mobile: "01861-676979", offMail: "murshidakanta@gmail.com", edu: "BA, LLB", gender: "Female", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2015", daysPerWeek: 6 },
  { sl: 3, eid: "1003", name: "AM Shmsuddula", desig: "Documentation Coordinator", dept: "Program & Operation", status: "Inactive", mobile: "01766-811240", offMail: "doc.coordinaror.leedo@gmail.com", edu: "MA", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2020", dos: "20-Apr-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 4, eid: "1004", name: "Md. Habibur Rahman", desig: "Accountant", dept: "Admin & Finance", status: "Active", mobile: "01733-336365", pMail: "habibsac1993@gmail.com", offMail: "habibrleedo@gmail.com", nid: "7789037731", dob: "05-Mar-1993", addr: "1st Floor, House No. 123/C, Road No. 4, South Pirerbag, Mirpur, Dhaka-1216", edu: "MBA", father: "Md. Mujibur Rahman", mother: "Mst. Nadira Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "05-Sep-2022", daysPerWeek: 6 },
  { sl: 5, eid: "1005", name: "Md. Zisan Rehman", desig: "Sr. Manager, Program & Partnership Development", dept: "Grants Acquisition", status: "Inactive", mobile: "01325-681272", pMail: "zrkhan09@hotmail.com", offMail: "zisan.leedo@gmail.com", nid: "1466381074", dob: "07-May-1991", addr: "House No. 64, 1st Floor, Darus Salam, Mirpur Road, Dhaka-1216", edu: "BBA", profEdu: "ACCA (F1-F7)", father: "Ansari Khan", mother: "Lily Islam", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "02-May-2024", dos: "30-May-2026", reason: "Resignation", daysPerWeek: 5 },
  { sl: 6, eid: "1006", name: "Md. Rashedul Hasan", desig: "HR & Admin Officer", dept: "Admin & Finance", status: "Inactive", mobile: "018518-34744", offMail: "rashed.leedo@gmail.com", edu: "MBA", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2021", dos: "30-Nov-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 7, eid: "1007", name: "Athui Marma", desig: "Monitoring Officer", dept: "Program & Operation", status: "Active", mobile: "01533-650126", pMail: "thuimarma06@gmail.com", offMail: "athoileedo26@gmail.com", nid: "19908417823000068", dob: "10-Dec-1990", addr: "13/2, Tollarbag, Indira Road, Dhaka", edu: "MA", father: "Ukyajai Marma", mother: "Kraminyu Marma", gender: "Female", rel: "Buddhism", nature: "Permanent", loc: "Head Office", doj: "05-Nov-2022", daysPerWeek: 6 },
  { sl: 8, eid: "1008", name: "Tawhid Ahmeed", desig: "Young Volunteer", dept: "Program & Operation", status: "Active", mobile: "01893-636383", offMail: "youngleader.leedobd2000@gmail.com", father: "Forhad Hossain", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2023", daysPerWeek: 5 },
  { sl: 9, eid: "1009", name: "Rone Ahammed", desig: "Logistics Officer", dept: "Admin & Finance", status: "Active", mobile: "01818-202173", offMail: "logistic.leedo@gmail.com", nid: "5529006917", dob: "13-Apr-1984", addr: "Osman Vandari Villa, House No. 37, Block B, Road No. 9, East Rasulupur, Kamrangir Char, Dhaka", edu: "HSC", father: "Late. Md. Osman Ali", mother: "Nurjahan Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "10-Dec-2022", daysPerWeek: 6 },
  { sl: 10, eid: "1010", name: "Ibrahim", desig: "Driver", dept: "Admin & Finance", status: "Active", mobile: "01764-614539", dob: "01-Jan-1989", addr: "Dewan Bari, West Rasulpur, KamrangirChar, Dhaka-1211", edu: "8 Pass", father: "Md. Abdul Kader", mother: "Morium Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2020", daysPerWeek: 6 },
  { sl: 11, eid: "1011", name: "Halima Akhter", desig: "Office Assistant", dept: "Admin & Finance", status: "Inactive", mobile: "01736-379581", nid: "9178813052", dob: "01-Apr-2004", addr: "Washpur, Keraniganj, Dhaka", edu: "5 Pass", father: "Monnor Ali", mother: "Jahanara Begum", gender: "Female", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "19-Oct-2025", dos: "10-Apr-2026", reason: "Termination", daysPerWeek: 6 },
  { sl: 12, eid: "1012", name: "Tanjila Akter Nila", desig: "Finance & Accounts Assistant", dept: "Admin & Finance", status: "Inactive", edu: "MBA", gender: "Female", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Feb-2023", dos: "30-Nov-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 13, eid: "1013", name: "Md. Sohel Rana", desig: "Manager", dept: "Program & Operation", status: "Active", mobile: "01728-790037", pMail: "msohelrana2@gmail.com", offMail: "sohelrana.leedo@gmail.com", nid: "5954027834", dob: "05-Aug-1992", addr: "House No. 37/1, Abdul Aziz Khan Road, West Jafrabad, Mohammadpur, Dhaka-1207", edu: "B.Sc", father: "Md. Ayub Ali", mother: "Most. Sufiya Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "28-Feb-2015", daysPerWeek: 6 },
  { sl: 14, eid: "1014", name: "Tania Akter", desig: "Assistant Home Super", dept: "Program & Operation", status: "Active", mobile: "01952-509518", offMail: "tania.leedo18@gmail.com", addr: "Village: Dhamusha, Post: Dashar, Kalkini, Madaripur", edu: "Alim", father: "Habibur Rahman", mother: "Rahiman", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "01-May-2015", daysPerWeek: 6 },
  { sl: 15, eid: "1015", name: "Parvin Akter", desig: "Mother", dept: "Program & Operation", status: "Active", mobile: "01919-490307", offMail: "parveen.leedo07@gmail.com", nid: "9107517592", dob: "06-Dec-1982", addr: "House No. 18/12, Polashi Colony, Lalbagh, Dhaka", edu: "Eight", father: "Md. Osman Ali", mother: "Mrs. Nurjahan", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "01-Jan-2020", daysPerWeek: 6 },
  { sl: 16, eid: "1016", name: "Vulu Rani Mollik", desig: "Cook", dept: "Program & Operation", status: "Active", mobile: "01752-841427", nid: "2843752227", dob: "01-Mar-1972", addr: "Village: Modonkhali, P.O. Churain, Munshiganj", edu: "SSC", father: "Late Porimol Dhali", mother: "Adori Rani", gender: "Female", rel: "Hinduism", nature: "Contractual", loc: "Peace Home", doj: "01-May-2015", daysPerWeek: 6 },
  { sl: 17, eid: "1017", name: "Nargis Akhter", desig: "Psycho-social Facilitator", dept: "Program & Operation", status: "Active", mobile: "01712-884445", offMail: "asknargis@gmail.com", nid: "5531756244", addr: "House No. 286/2, East Rampura, Khilgaon, Dhaka", edu: "BA", father: "Chan Mia", mother: "Rahima Khatoon", gender: "Female", rel: "Islam", nature: "Part Time", loc: "Peace Home", doj: "01-Mar-2022", daysPerWeek: 3, inTime: "10:00 AM", outTime: "02:00 PM", dailyHours: 4 },
  { sl: 18, eid: "1018", name: "Md. Tajudddin", desig: "Music Teacher", dept: "Program & Operation", status: "Active", mobile: "019157-11125", edu: "Singer", gender: "Male", rel: "Islam", nature: "Part Time", loc: "Peace Home", doj: "08-Feb-2024", daysPerWeek: 3, inTime: "10:00 AM", outTime: "02:00 PM", dailyHours: 4 },
  { sl: 19, eid: "1019", name: "Happy Akter", desig: "Music Teacher", dept: "Program & Operation", status: "Active", mobile: "013122-45976", edu: "Singer", gender: "Female", rel: "Islam", nature: "Part Time", loc: "Peace Home", doj: "08-Feb-2024", daysPerWeek: 3, inTime: "10:00 AM", outTime: "02:00 PM", dailyHours: 4 },
  { sl: 20, eid: "1020", name: "Nowshad Mia", desig: "Security Guard", dept: "Program & Operation", status: "Inactive", mobile: "01851-879627", edu: "Literate", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "01-Jan-2021", dos: "31-Dec-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 21, eid: "1021", name: "Md. Shahin", desig: "Security Guard", dept: "Program & Operation", status: "Inactive", mobile: "01939-673467", edu: "Literate", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "01-Jan-2021", dos: "31-Dec-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 22, eid: "1022", name: "Sahela Khan Rimu", desig: "Mother", dept: "Program & Operation", status: "Active", mobile: "01813-253769", pMail: "rimukhansahela07@gmail.com", offMail: "rimu.leedo69@gmail.com", addr: "456, Mirhazirbagh, Madrasa Road, Jatrabari, Dhaka-1204", edu: "HSC", father: "Late Abdur Rashed Khan", mother: "Late Sadeka Khatun", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kamalapur)", doj: "06-Apr-2021", daysPerWeek: 6 },
  { sl: 23, eid: "1023", name: "Md. Masud", desig: "Social Mobilizer (Incharge)", dept: "Program & Operation", status: "Active", mobile: "01304-035081", pMail: "mr669975@gmail.com", offMail: "masud.leedo81@gmail.com", nid: "2408638209", dob: "12-Oct-2002", addr: "336/E, South Jatrabari, Dhaka", edu: "BA (Running)", father: "Razzaq Howlader", mother: "Sufia Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Shelter (Kamalapur)", doj: "05-Jun-2021", daysPerWeek: 6 },
  { sl: 24, eid: "1024", name: "Md. Mahafujur Rahman", desig: "Social Mobilizer", dept: "Program & Operation", status: "Inactive", mobile: "01907-572478", pMail: "farabi87192@gmail.com", nid: "7352659002", dob: "20-Sep-1999", addr: "Aorabunia, Kathalia, Jhalakati", edu: "B.Sc. (Running)", father: "Md. Nasir Uddin Howlader", mother: "Sajeda Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Shelter (Kamalapur)", doj: "10-Feb-2026", dos: "31-Mar-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 25, eid: "1025", name: "Rupali Akter", desig: "Cook cum Mother", dept: "Program & Operation", status: "Inactive", mobile: "01703-327055", edu: "SSC", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kamalapur)", doj: "01-Jan-2022", dos: "30-Nov-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 26, eid: "1026", name: "Sorna Akter", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", edu: "HSC", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "01-Jan-2022", dos: "30-Nov-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 27, eid: "1027", name: "Md. Suzan Mia", desig: "Social Mobilizer (Incharge)", dept: "Program & Operation", status: "Inactive", mobile: "01750-444816", pMail: "sujonhasan823@gmail.com", nid: "20044930959107021", dob: "20-Apr-2004", addr: "Washpur Garden City, Keraniganj, Dhaka", edu: "HSC", father: "Md. Aiyub Ali", mother: "Sufiya Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "01-Apr-2022", dos: "24-May-2026", reason: "Termination", daysPerWeek: 6 },
  { sl: 28, eid: "1028", name: "Saidur Rahman Sajan", desig: "Social Mobilizer", dept: "Program & Operation", status: "Active", mobile: "01632-147709", offMail: "said.leedo14@gmail.com", nid: "20013090802101465", dob: "01-Jun-2001", addr: "Village: Ujanchar, Ishwarganj, Mymensingh", edu: "BBA (Running)", father: "Md. Idris Ali", mother: "Rahela Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "20-Mar-2022", daysPerWeek: 6 },
  { sl: 29, eid: "1029", name: "Lamia Akter", desig: "Shelter Mother", dept: "Program & Operation", status: "Inactive", mobile: "01999-307556", pMail: "la183548222@gmail.com", edu: "HSC", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "01-Jan-2022", dos: "30-Oct-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 30, eid: "1030", name: "Shahnaz Parvin", desig: "Cook", dept: "Program & Operation", status: "Active", mobile: "01934-229459", nid: "7817879682", dob: "10-Jul-1990", addr: "Chunkutia Paschimpara, Shuvadda, Keraniganj, Dhaka-1310", edu: "Literate", father: "Md. Saj Uddin", mother: "Nasima Akter", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "18-Nov-2019", daysPerWeek: 6 },
  { sl: 31, eid: "1031", name: "Md. Shahabuddin", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", mobile: "01768-462517", pMail: "sha565975@gmail.com", nid: "1003027412", dob: "01-Jan-1978", addr: "Chunkutia West para, South Keranigonj, Dhaka-1310", edu: "MA", father: "Late. Md. Nazem Ali", mother: "Krimonnessa", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "01-Feb-2020", dos: "15-Feb-2026", reason: "Death", daysPerWeek: 6 },
  { sl: 32, eid: "1032", name: "Nazirul Islam Opu", desig: "Senior Social Mobilizer (Incharge)", dept: "Program & Operation", status: "Active", mobile: "01615-190173", offMail: "nazirulopu.leedo2019@gmail.com", edu: "Class-10", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Mirpur)", doj: "15-Jun-2020", daysPerWeek: 6 },
  { sl: 33, eid: "1033", name: "Masaiching Marma", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", mobile: "01833-451932", nid: "4214835114", dob: "12-Oct-2002", addr: "Village: Dongnala Noapara, Kaptai, Rangamati", edu: "BA (Running)", father: "Kyasakhay Marma", mother: "Chingsama Marma", gender: "Female", rel: "Buddhism", nature: "Contractual", loc: "School Under the Sky (Mirpur)", doj: "25-Jan-2025", dos: "30-Jun-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 34, eid: "1034", name: "Leo Gomes", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01618-235848", offMail: "leo.leedo48@gmail.com", nid: "3313417717329", dob: "18-Jun-1980", addr: "176/1, Tejkunipara, Tejgaon, Dhaka-1215", edu: "SSC", father: "Late Amal Gomes", mother: "Sushama Gomes", gender: "Male", rel: "Christianity", nature: "Contractual", loc: "School Under the Sky (Tejgaon)", doj: "09-Oct-2021", daysPerWeek: 6 },
  { sl: 35, eid: "1035", name: "Shuchitra Rani Barman", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01939-849787", nid: "5617057354442", dob: "12-Dec-1978", addr: "Village: Kholli Dhankora, Saturia, Manikganj", edu: "SSC", father: "Amor Chad Barman", mother: "Bina Rani Barman", gender: "Female", rel: "Hinduism", nature: "Contractual", loc: "School Under the Sky (RayerBazar)", doj: "01-Feb-2018", daysPerWeek: 6 },
  { sl: 36, eid: "1036", name: "Md. Nizam Hossain", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01782-327102", pMail: "nizamhossainleedo5252@gmail.com", offMail: "nizamhossain7102@gmail.com", nid: "20052692533153890", dob: "30-Dec-2005", addr: "Pabna House Goli, Rayer Bazar, Mohammadpur, Dhaka", edu: "BA (Running)", father: "Joynal Abedin", mother: "Kohinur Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (RayerBazar)", doj: "15-Jan-2018", daysPerWeek: 6 },
  { sl: 37, eid: "1037", name: "Jesmin Akter", desig: "Office Assistant", dept: "Program & Operation", status: "Active", mobile: "01950-880717", offMail: "jesminrisberg@gmail.com", nid: "A21391785", dob: "02-Oct-2004", addr: "Char Patro Khata, Chilmari, Kurigram", edu: "High School", father: "Md. Ayub Ali", mother: "Most. Sufiya Begum", gender: "Female", rel: "Islam", nature: "Part Time", loc: "Peace Home", doj: "12-Jan-2022", daysPerWeek: 3, inTime: "09:00 AM", outTime: "02:00 PM", dailyHours: 5 },
  { sl: 38, eid: "1038", name: "Kazi Tahmin Sultana", desig: "Special Educator", dept: "Program & Operation", status: "Active", mobile: "01619-845002", pMail: "zaheenasif2006@gmail.com", offMail: "ktahmin.leedo02@gmail.com", nid: "2694813857674", dob: "27-Dec-1973", addr: "House No. 204, Arshinagar Housing, Keraniganj, Dhaka", edu: "MSS, MSEd", father: "Md. Asif Razzak", mother: "Late Saiyeda Mansura Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Inclusive School", doj: "08-Jan-2022", daysPerWeek: 5 },
  { sl: 39, eid: "1039", name: "Tahmina Haque Tonima", desig: "Special Educator", dept: "Program & Operation", status: "Active", mobile: "01962-678701", offMail: "tonima.leedo81@gmail.com", nid: "19962613860000115", dob: "01-Jun-1996", addr: "House No. 22/A, Arshinagar, Keraniganj, Dhaka-1213", edu: "BA", father: "Md. Fazlul Haque", mother: "Mukta Haque", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Inclusive School", doj: "08-Jan-2022", daysPerWeek: 5 },
  { sl: 40, eid: "1040", name: "Ruksana Akter", desig: "Sewing Teacher", dept: "Program & Operation", status: "Active", mobile: "0189-3468570", nid: "2692858515787", dob: "02-Dec-1985", addr: "Arshinagar, Keraniganj, Dhaka", edu: "HSC", father: "Md. Hossain Ahmed", mother: "Rokeya Hossain", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Inclusive School", doj: "13-Apr-2025", daysPerWeek: 5 },
  { sl: 41, eid: "1041", name: "Maksuda", desig: "Sewing Instructor", dept: "Program & Operation", status: "Inactive", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Inclusive School", doj: "01-Jan-2023", dos: "30-Sep-2025", reason: "Contract End", daysPerWeek: 5 },
  { sl: 42, eid: "1042", name: "Tahasin Haque", desig: "Documentation Officer", dept: "Program & Operation", status: "Inactive", mobile: "018503-27674", pMail: "rayhanoran7@gmail.com", offMail: "doc.coordinator.leedo@gmail.com", nid: "8262526976", dob: "27-Dec-2002", addr: "Ghatarchar, Keraniganj, Dhaka", edu: "BBA", father: "Md. Emdadul Haque", mother: "Yeanoor", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "07-Aug-2025", dos: "09-Apr-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 43, eid: "1043", name: "Sobuj", desig: "Security Guard", dept: "Program & Operation", status: "Active", nid: "19945116523000016", dob: "03-Jan-1994", addr: "Ramonpur, Ramganj, Lakshmipur", father: "Musabbor Hossain", mother: "Rokeya Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "15-Oct-2025", daysPerWeek: 6 },
  { sl: 44, eid: "1044", name: "Rehana Parvin", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01710-494058", nid: "7783707305", dob: "02-Jan-1977", addr: "House No. 251/1, East Goran, Khilgaon, Dhaka", edu: "MSS", father: "Late Md. Hossain", mother: "Late Nurjahan Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "20-Jul-2025", daysPerWeek: 6 },
  { sl: 45, eid: "1045", name: "Sworna Akter", desig: "ICT Instructor", dept: "Program & Operation", status: "Inactive", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "01-Jan-2024", dos: "15-Jan-2026", reason: "Resignation", daysPerWeek: 5 },
  { sl: 46, eid: "1046", name: "Kohinoor Khatun", desig: "Program Coordinator", dept: "Program & Operation", status: "Inactive", mobile: "01732-765239", pMail: "kohinoor277@gmail.com", offMail: "kohinoor.leedo@gmail.com", nid: "3701219168", dob: "05-Jul-1975", addr: "Gillatala, Khanjahan Ali, Khulna", edu: "M.Com", father: "SK Montaz Uddin", mother: "Tahera Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "04-Aug-2025", dos: "28-Feb-2026", reason: "Termination", daysPerWeek: 6 },
  { sl: 47, eid: "1047", name: "Giasuddin Matbor", desig: "Security Guard", dept: "Program & Operation", status: "Inactive", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "08-Jul-2025", dos: "20-Aug-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 48, eid: "1048", name: "Kathy Marma", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", mobile: "01888-636641", nid: "9168594902", dob: "05-Mar-2004", addr: "Mrongdong Para, Rangamati", edu: "SSC", father: "Ajumong Marma", mother: "Ukra Jai Marma", gender: "Female", rel: "Buddhism", nature: "Contractual", loc: "School Under the Sky (Airport)", doj: "04-Sep-2025", dos: "30-May-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 49, eid: "1049", name: "Md. Sane Dewan", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", mobile: "01795-693651", pMail: "mdnerobislam320@gmail.com", nid: "5574758982", dob: "24-Aug-2004", addr: "Otra, Wazirpur, Barishal", edu: "HSC", father: "Md. Faruk Dewan", mother: "Mahmuda Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Airport)", doj: "04-Sep-2025", dos: "30-Jun-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 50, eid: "1050", name: "Zubayer Mabrur", desig: "Social Mobilizer", dept: "Program & Operation", status: "Inactive", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Mirpur)", doj: "01-Jan-2024", dos: "30-Sep-2025", reason: "Resignation", daysPerWeek: 6 },
  { sl: 51, eid: "1051", name: "Md. Nazmul Karim", desig: "Director, Grants Acquisition & Proposal Development", dept: "Grants Acquisition", status: "Inactive", mobile: "01917-960273", pMail: "nazmulhelal@gmail.com", offMail: "danpnazmul.leedo@gmail.com", nid: "8233065245", dob: "28-Feb-1963", addr: "Mohammadpur, Dhaka", edu: "MSS", father: "Late A.K.M. Mostafa", mother: "Jahanara Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "07-Sep-2025", dos: "12-May-2026", reason: "Death", daysPerWeek: 5 },
  { sl: 52, eid: "1052", name: "AKM Azizur Rahman", desig: "Co-ordinator, Partnership", dept: "Grants Acquisition", status: "Active", mobile: "01675-633010", offMail: "azizrahman.leedo@gmail.com", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "11-Sep-2025", daysPerWeek: 5 },
  { sl: 53, eid: "1053", name: "Abdus Sattar", desig: "Mobile Servicing Instructor", dept: "Program & Operation", status: "Inactive", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "01-Jan-2024", dos: "31-Dec-2025", reason: "Contract End", daysPerWeek: 5 },
  { sl: 54, eid: "1054", name: "Shamsunnahar", desig: "Sewing Trainer", dept: "Program & Operation", status: "Inactive", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "01-Jan-2024", dos: "31-Dec-2025", reason: "Contract End", daysPerWeek: 5 },
  { sl: 55, eid: "1055", name: "Runa Begum", desig: "Mother", dept: "Program & Operation", status: "Inactive", nid: "8650775276", dob: "01-Feb-1981", addr: "ChorBishonath, Munshiganj", edu: "5 pass", father: "Araj Ali Sarkar", mother: "Saleha Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kamalapur)", doj: "11-Sep-2025", dos: "28-Feb-2026", reason: "Termination", emg: "0199-7287514", daysPerWeek: 6 },
  { sl: 56, eid: "1056", name: "Fouzia Ahmed Polly Mazumder", desig: "Communication & Media Manager", dept: "Program & Operation", status: "Inactive", mobile: "01977-415023", pMail: "fo.ahmed632@gmail.com", offMail: "communicationmedialeedo@gmail.com", nid: "7831708263", dob: "01-Jan-2001", addr: "Nikunjo 2, Khilkhet, Dhaka", edu: "MSS", father: "Md. Fozol Ahmed Mozumder", mother: "Hasina Akter", gender: "Female", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Sep-2025", dos: "13-Mar-2026", reason: "Resignation", daysPerWeek: 5 },
  { sl: 57, eid: "1057", name: "Md. Omar Faruque", desig: "Manager HR & Admin", dept: "Admin & Finance", status: "Active", mobile: "016714-32484", pMail: "Omar.Faruque.Jumman@gmail.com", offMail: "hr.leedo2000@gmail.com", nid: "32380776240", addr: "House No. 427/6, Jawchar, Kamrangir Char, Dhaka", edu: "M.Sc.", profEdu: "PGDHRM", father: "Late. Md. Abdus Sattar", mother: "Mahmuda Khatun", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jan-2026", emg: "01731-784421", daysPerWeek: 6 },
  { sl: 58, eid: "1058", name: "Moin Ahmed", desig: "Program Coordinator", dept: "Program & Operation", status: "Inactive", mobile: "01954-261500", pMail: "moin.hrm.ahmed@gmail.com", offMail: "prgcoord.leedo@gmail.com", nid: "6884863819", dob: "24-Apr-1994", addr: "West Rampura, Dhaka", edu: "MBA(HRM)", father: "Md. Mofizur Rahman", mother: "Nazma Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Feb-2026", dos: "31-Mar-2026", reason: "Termination", emg: "01711-261845", daysPerWeek: 6 },
  { sl: 59, eid: "1059", name: "Mim Akter Oishi", desig: "Teacher", dept: "Program & Operation", status: "Active", mobile: "01929-540167", pMail: "mimakteroishi56472@gmail.com", nid: "20062692533442018", dob: "25-Jan-2006", addr: "Ghatarchar, Keraniganj Model, Dhaka-1310", edu: "HSC", father: "Md. Kabir Hosan", mother: "Makshuda Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "31-Jul-2025", daysPerWeek: 5 },
  { sl: 60, eid: "1060", name: "Safia Akther", desig: "Handicraft & Carpenter Teacher", dept: "Program & Operation", status: "Inactive", mobile: "01722-143661", nid: "1023824418", dob: "20-Jul-1985", addr: "Khejurbagh, Keraniganj", edu: "HSC", father: "Motiar Rohaman", mother: "Jorina Khatun", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Vocational Trade School", doj: "01-Feb-2026", dos: "15-Mar-2026", reason: "Termination", daysPerWeek: 5 },
  { sl: 61, eid: "1061", name: "Sharmin Akter", desig: "Sewing Teacher", dept: "Program & Operation", status: "Active", mobile: "01623-841818", nid: "8224695661", dob: "08-Aug-1995", addr: "Pargandaria, Keraniganj", edu: "MA", father: "Md. Karim", mother: "Feroza Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Vocational Trade School", doj: "01-Feb-2026", daysPerWeek: 5 },
  { sl: 62, eid: "1062", name: "Sharmin Akter Puspo", desig: "Beautification Teacher", dept: "Program & Operation", status: "Active", mobile: "01798-852216", nid: "2357503933", dob: "29-Dec-1997", addr: "Aganagar, Keraniganj, Dhaka", edu: "HSC", father: "Abul Basar Bachu", mother: "Nazma", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Vocational Trade School", doj: "01-Feb-2026", daysPerWeek: 5 },
  { sl: 63, eid: "1063", name: "Mohammed Sakitul Hider", desig: "Football Coach", dept: "Program & Operation", status: "Active", mobile: "01830-381677", pMail: "biplobmiaty@gmail.com", nid: "2377078809", dob: "04-Aug-1976", addr: "24/1, Station Road, Tejgaon, Dhaka", edu: "HSC", father: "Late Abdul Jalil", mother: "Samsun Nahar", gender: "Male", rel: "Islam", nature: "Part Time", loc: "School Under the Sky (Airport)", doj: "16-Feb-2026", daysPerWeek: 3, inTime: "07:30 AM", outTime: "11:30 AM", dailyHours: 4 },
  { sl: 64, eid: "1064", name: "Maloti Bishwas", desig: "Cook", dept: "Program & Operation", status: "Active", mobile: "0133-9257825", nid: "7365356885", dob: "12-Dec-2001", addr: "South Mugda, Dhaka-1214", edu: "Class - 9", father: "Pronoy Bisas", mother: "Shamla Bisas", gender: "Female", rel: "Hinduism", nature: "Contractual", loc: "Shelter (Kamalapur)", doj: "11-Aug-2026", daysPerWeek: 6 },
  { sl: 65, eid: "1065", name: "Hridoy", desig: "Mobile Toilet Operator", dept: "Program & Operation", status: "Inactive", mobile: "01786-228800", dob: "01-Jan-2006", addr: "South Mugdapara, Mugda, Dhaka", edu: "Class- 5", father: "Md. Harun", mother: "Mst. Laili Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "01-Jan-2024", dos: "30-Jun-2026", daysPerWeek: 6 },
  { sl: 66, eid: "1066", name: "Robiul Hasan", desig: "Office Assistant", dept: "Program & Operation", status: "Inactive", nid: "20091591613111114", dob: "05-Feb-2009", addr: "Jagatpur, Kachua, Chandpur", father: "Md. Manna", mother: "Rahima Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kodomtoli)", doj: "01-Jan-2024", dos: "30-Apr-2026", reason: "Dismissed", daysPerWeek: 6 },
  { sl: 67, eid: "1067", name: "Md. Rayhan Khan Hira", desig: "Communication & Media Manager", dept: "Program & Operation", status: "Active", mobile: "0133-4112941", pMail: "rronooffice25@gmail.com", offMail: "communicationmedialeedo@gmail.com", nid: "6015197749", dob: "25-Jul-1999", addr: "Chandrima M.T.", edu: "BSS Hon's", father: "Md. Habib Khan", mother: "Pratiua Rani Sarkar", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "29-Mar-2026", emg: "01518-900864", daysPerWeek: 6 },
  { sl: 68, eid: "1068", name: "Wahid Hasan Niloy", desig: "ICT Instructor", dept: "Program & Operation", status: "Active", mobile: "0179-7654700", pMail: "wahidhasan019@gmail.com", nid: "2431250568", dob: "26-Nov-2005", addr: "College Road, Kamrangirchar, Dhaka", edu: "BBA (Running)", father: "Hasan Mehedi", mother: "Nasrin Akter", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Vocational Trade School", doj: "01-Apr-2026", daysPerWeek: 5 },
  { sl: 69, eid: "1069", name: "Soumitra Kumar Shil", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "0172-2271624", pMail: "soumitrakumarshl7845@gmail.com", nid: "8718776951", dob: "20-Dec-2004", addr: "Kazi Abdur Roufe, KaltaBazar, Dhaka", edu: "BA (Running)", father: "Arabinda Chandra Shil", mother: "Shukla Rani Shil", gender: "Male", rel: "Hinduism", nature: "Contractual", loc: "School Under the Sky (Kodomtoli)", doj: "01-Apr-2026", daysPerWeek: 6 },
  { sl: 70, eid: "1070", name: "Forhad Ali", desig: "Social Mobilizer", dept: "Program & Operation", status: "Active", mobile: "01516-097997", pMail: "forhadbabu44@gmail.com", nid: "3767930161", dob: "08-Jul-2001", addr: "Matiakura, Sreebordi, Sherpur", edu: "BBA", father: "Md. Abdur Razzak", mother: "Feroza", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "01-Apr-2026", daysPerWeek: 6 },
  { sl: 71, eid: "1071", name: "Md. Asadullah", desig: "Cricket Coach", dept: "Program & Operation", status: "Active", mobile: "01797-038112", pMail: "asadhossain@gmail.com", nid: "2858405521", dob: "08-Mar-1997", addr: "Madda Char, Keraniganj, Dhaka", edu: "BA", father: "Md. Sadekul Islam", mother: "Mst. Alema Khatun", gender: "Male", rel: "Islam", nature: "Part Time", loc: "Peace Home", doj: "01-Apr-2026", daysPerWeek: 3, inTime: "08:00 AM", outTime: "12:00 PM", dailyHours: 4 },
  { sl: 72, eid: "1072", name: "Hafiza Begum", desig: "Office Assistant", dept: "Admin & Finance", status: "Inactive", mobile: "0140-4342932", addr: "Nagarkanda, Faridpur", edu: "Class-10", father: "Khokon Matabbar", mother: "Rabeya Begum", gender: "Female", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "07-Apr-2026", dos: "18-Apr-2026", reason: "Termination", daysPerWeek: 6 },
  { sl: 73, eid: "1073", name: "Ibrahim Khalil", desig: "Social Mobilizer", dept: "Program & Operation", status: "Inactive", mobile: "01753-790100", pMail: "kholilcbrahim455@gmail.com", nid: "6918176410", dob: "28-Aug-2004", addr: "West Rasulpur, Narayanganj", edu: "HSC", father: "Md. Younus", mother: "Mahmuda", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kodomtoli)", doj: "06-Apr-2026", dos: "24-May-2026", reason: "Resignation", daysPerWeek: 6 },
  { sl: 74, eid: "1074", name: "Ruma Akter", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", mobile: "01927-929893", nid: "7813775850", dob: "19-Jan-1997", addr: "Turag Housing, Mohammadpur, Dhaka", edu: "MA", father: "Mohammad Ali", mother: "Moslema Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Mirpur)", doj: "18-Apr-2026", dos: "31-Jul-2026", reason: "Resignation", emg: "0154-0112034", daysPerWeek: 6 },
  { sl: 75, eid: "1075", name: "Farhana Akter", desig: "Program Coordinator", dept: "Program & Operation", status: "Active", mobile: "01617-155535", pMail: "farhanamanagement55@gmail.com", nid: "4640703239", dob: "12-Apr-1995", addr: "Town Hall, Mohammadpur, Dhaka", edu: "BBA", profEdu: "PGDPM", father: "Deen Mohammad Dulal", mother: "Pirara Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "23-Apr-2026", emg: "0140-4674856", daysPerWeek: 6 },
  { sl: 76, eid: "1076", name: "Mahabob Alam", desig: "Intern - Content Creator", dept: "Program & Operation", status: "Inactive", mobile: "01817-377931", pMail: "Mahabobaiamsijan2003@gmail.com", addr: "Bosila, Dhaka", edu: "BSS (Running)", father: "Shah Alam", mother: "Seren", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "25-Apr-2026", dos: "31-May-2026", reason: "Resignation", emg: "0179-0363394", daysPerWeek: 5 },
  { sl: 77, eid: "1077", name: "Mariyam Khanam", desig: "Shelter Mother", dept: "Program & Operation", status: "Inactive", mobile: "0198-5560011", addr: "Khejurbag, Keraniganj, Dhaka", edu: "HSC", father: "Md. Matiyar Rahman", mother: "Khadiza Khanam", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "01-Jan-2025", dos: "24-May-2026", reason: "Termination", daysPerWeek: 6 },
  { sl: 78, eid: "1078", name: "Tasfina Hossain", desig: "Handicraft & Carpenter Teacher", dept: "Program & Operation", status: "Inactive", mobile: "016757-03510", pMail: "tasfinahossain7@gmail.com", nid: "5963509558", dob: "07-Nov-1992", addr: "Keraniganj, Dhaka", edu: "MA", father: "Md. Abdul Hossain", mother: "Begum Hannama Hossain", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Vocational Trade School", doj: "01-May-2026", dos: "31-Aug-2026", reason: "Resignation", daysPerWeek: 5 },
  { sl: 79, eid: "1079", name: "Sazzad Hosen", desig: "Assistant Accountant", dept: "Admin & Finance", status: "Active", mobile: "01680-882718", pMail: "sazzadhosen0153470@gmail.com", nid: "5078356473", dob: "19-Oct-1993", addr: "Nizam Bagh, Kamrangirchar, Dhaka", edu: "MA", father: "Md. Amzad Hosen", mother: "Aysha Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "01-Jun-2026", emg: "01684-210380", daysPerWeek: 6 },
  { sl: 80, eid: "1080", name: "Belal Ahmed", desig: "Documentation Coordinator", dept: "Program & Operation", status: "Active", mobile: "01749-692780", pMail: "a.belal27@outlook.com", nid: "5056977936", dob: "07-Oct-1993", addr: "Nakhalpara, Dhaka", edu: "BSS", profEdu: "PMIR", father: "Late. Abdul Hai", mother: "Rajia Begum", gender: "Male", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "17-Jun-2026", emg: "0188-6435369", daysPerWeek: 6 },
  { sl: 81, eid: "1081", name: "Mim Akter", desig: "Office Assistant", dept: "Admin & Finance", status: "Active", mobile: "01623-868173", nid: "6932899096", dob: "04-Aug-2002", addr: "Ghatarchar, Keraniganj, Dhaka", father: "Ali Ullah", mother: "Late Kohinoor Begum", gender: "Female", rel: "Islam", nature: "Permanent", loc: "Head Office", doj: "16-Jun-2026", emg: "01933-182700", daysPerWeek: 6 },
  { sl: 82, eid: "1082", name: "Shamima Yeasmin Alo", desig: "Social Mobilizer", dept: "Program & Operation", status: "Inactive", mobile: "01683-659817", pMail: "shamimaaloalo@gmail.com", nid: "910456974", dob: "08-Aug-1992", addr: "Nobinogor Housing, Mohammadpur", edu: "HSC", father: "Late Abdur Rashid", mother: "Sakina Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "21-Jun-2026", dos: "30-Jun-2026", reason: "Unauthorised", emg: "01869-148417", daysPerWeek: 6 },
  { sl: 83, eid: "1083", name: "Subrina Rahman", desig: "Street Educator", dept: "Program & Operation", status: "Inactive", mobile: "01315-374452", pMail: "subrina628@gmail.com", nid: "8729731011", dob: "23-Jan-2004", addr: "Old town, Narinda", edu: "HSC", father: "Md. Ashrafur Rahman", mother: "Aysha Rahman", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kodomtoli)", doj: "21-Jun-2026", dos: "14-Jul-2026", reason: "Unauthorised", emg: "01318-389308", daysPerWeek: 6 },
  { sl: 84, eid: "1084", name: "Md. Tanveer Sarder", desig: "Social Mobilizer", dept: "Program & Operation", status: "Active", mobile: "01580-935537", pMail: "tanvir.dada254@gmail.com", nid: "8254732426", dob: "05-Aug-1998", addr: "66/A, Indira Road, Farmgate, Dhaka", edu: "BBA", father: "Md. Dulal Sarder", mother: "Firoza Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Tejgaon)", doj: "21-Jun-2026", emg: "0186-2133006", daysPerWeek: 6 },
  { sl: 85, eid: "1085", name: "Abdulla Al Hasan", desig: "Social Mobilizer", dept: "Program & Operation", status: "Inactive", mobile: "01324-227382", pMail: "shagorhasan197@gmail.com", dob: "01-Sep-2001", addr: "Bashundhara R/A, Dhaka", edu: "HSC", father: "Late Ramiz Uddin", mother: "Mst. Halima Akter", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kamalapur)", doj: "21-Jun-2026", dos: "30-Jun-2026", reason: "Resignation", emg: "0164-4057003", daysPerWeek: 6 },
  { sl: 86, eid: "1086", name: "Noor Muhammad Fahim", desig: "Social Mobilizer", dept: "Program & Operation", status: "Inactive", mobile: "01515-685090", pMail: "nmfivafi@gmail.com", nid: "1509622856", dob: "17-Nov-2000", addr: "Kallayanpur, Mirpur", edu: "BSS", father: "Md. Jalal Uddin", mother: "Tahmina Nargis", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Airport)", doj: "21-Jun-2026", dos: "31-Aug-2026", reason: "Resignation", emg: "0173-4850495", daysPerWeek: 6 },
  { sl: 87, eid: "1087", name: "Tahmina Akter", desig: "Shelter Mother", dept: "Program & Operation", status: "Inactive", mobile: "019852-75187", pMail: "tahminaaktar2062661@gmail.com", nid: "1507969796", dob: "27-Dec-1997", addr: "Kamrangirchar, Dhaka", edu: "MSS", father: "Tota Mia", mother: "Shahanaj Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Shelter (Kodomtoli)", doj: "24-Jun-2026", dos: "31-Aug-2026", reason: "Resignation", emg: "01611-141613", daysPerWeek: 6 },
  { sl: 88, eid: "1088", name: "Abdullah Al Nafi", desig: "Content Creator", dept: "Program & Operation", status: "Active", mobile: "01595-047832", pMail: "alexabnafi@gmail.com", nid: "9182274549", dob: "23-Apr-2007", addr: "South Keraniganj, Dhaka", edu: "BSS", father: "Abdul Hamid Biswash", mother: "Mahmuda Khan Kona", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "25-Jun-2026", emg: "01763-502254", daysPerWeek: 6 },
  { sl: 89, eid: "1089", name: "A.K.M. Mizanur Rahman", desig: "Fund Acquisition Manager", dept: "Grants Acquisition", status: "Active", mobile: "0197-9805641", pMail: "gipmiz69@gmail.com", nid: "6405135572", dob: "01-Nov-1969", addr: "Adabor, Dhaka", edu: "MSS", father: "Late. Md. Sofiullah", mother: "Saleha Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "01-Jul-2026", emg: "01976-757332", daysPerWeek: 5 },
  { sl: 90, eid: "1090", name: "Fabliha Mahfuz", desig: "Fund Acquisition Manager", dept: "Grants Acquisition", status: "Active", mobile: "01763-433819", pMail: "fablihamahfuz38@gmail.com", offMail: "fablihaleedo@gmail.com", nid: "4655506824", dob: "03-Jul-1997", addr: "Mirpur DOHS, Dhaka", edu: "MDS", father: "A.K.M. Mahfuzul Haque", mother: "Israt Haque", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "11-Jul-2026", emg: "0167-6152621", daysPerWeek: 5 },
  { sl: 91, eid: "1091", name: "Nargis Akter", desig: "Cook", dept: "Program & Operation", status: "Active", mobile: "01913-550484", pMail: "n01913550484@gmail.com", nid: "5107687674", dob: "25-Dec-1997", addr: "Haluyaghat, Mymensingh", edu: "MSS", father: "Late. Bahar Uddin", mother: "Salma Khatun", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "14-Jul-2026", daysPerWeek: 6 },
  { sl: 92, eid: "1092", name: "Sharmin Rahman", desig: "ICT Instructor", dept: "Program & Operation", status: "Active", mobile: "01533-618176", pMail: "sharmnRahman055@gmail.com", nid: "3311295376", dob: "19-Jun-2001", addr: "Rayerbazar, Dhaka", edu: "BBA", father: "Mojbor Rahman", mother: "Nurjahan Begum", gender: "Female", rel: "Islam", nature: "Contractual", loc: "Peace Home", doj: "26-Jul-2026", emg: "0195-6896989", daysPerWeek: 5 },
  { sl: 93, eid: "1093", name: "Milton Miya", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01317-192291", pMail: "mdmiltonmiya91@gmail.com", nid: "6468892002", dob: "19-Mar-2004", addr: "Sutrapur, Dhaka", edu: "BA", father: "Mizanur Rahman", mother: "Most. Morzina Begum", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Kodomtoli)", doj: "26-Jul-2026", emg: "01717-584072", daysPerWeek: 6 },
  { sl: 94, eid: "1094", name: "Sadia Yasmin Meghla", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01937-084424", nid: "8725036514", dob: "09-Sep-2005", addr: "Mongla, Bagerhat", edu: "HSC", father: "Alamgir Sagor Hawlader", mother: "Afroza Akter", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Airport)", doj: "18-Aug-2026", daysPerWeek: 6 },
  { sl: 95, eid: "1095", name: "Monirul Islam", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01577-528412", pMail: "smmonrulislam318@gmail.com", nid: "9174922949", dob: "16-Jan-2005", addr: "Mongla, Bagerhat", edu: "HSC", father: "Rezaul Sheikh", mother: "Seauli Begom", gender: "Male", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Airport)", doj: "18-Aug-2026", daysPerWeek: 6 },
  { sl: 96, eid: "1096", name: "Nabila Akter", desig: "Street Educator", dept: "Program & Operation", status: "Active", mobile: "01815-452923", dob: "30-Aug-2009", addr: "Mazar Road, Mirpur, Dhaka-1216", edu: "Eight Pass", father: "Md. Shah Jalal", mother: "Kamrunnahar", gender: "Female", rel: "Islam", nature: "Contractual", loc: "School Under the Sky (Mirpur)", doj: "16-Aug-2026", daysPerWeek: 6 },
  { sl: 97, eid: "1097", name: "Monirul Islam", desig: "Security Guard", dept: "Program & Operation", status: "Active", mobile: "01999-690906", nid: "2381401898", addr: "Shamlapur, Keraniganj, Dhaka", father: "Adil Uddin", mother: "Lutfunnahar", gender: "Male", rel: "Islam", nature: "Contractual", loc: "Head Office", doj: "20-Aug-2026", daysPerWeek: 6 }
];

// Helper to determine system role
function determineRole(eid: string, offMail?: string): UserRole {
  if (eid === "1001" || eid === "1002") return "SUPER ADMIN";
  if (eid === "1057" || eid === "1006" || offMail === "hr.leedo2000@gmail.com") return "HR ADMIN";
  return "EMPLOYEE";
}

// Convert RawStaff to standard Employee
export const LEEDO_ALL_EMPLOYEES: Employee[] = rawList.map((r) => {
  const daysPerWeek = r.daysPerWeek || (r.nature === "Part Time" ? 3 : 6);
  
  // Schedule days: 0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat
  // 6 days: Sat–Thu (6, 0, 1, 2, 3, 4) - Fri(5) is off
  // 5 days: Sat–Wed (6, 0, 1, 2, 3) or Sun–Thu
  // 3 days: Sat, Mon, Wed (6, 1, 3)
  let scheduleDays = [6, 0, 1, 2, 3, 4];
  if (daysPerWeek === 5) {
    scheduleDays = [6, 0, 1, 2, 3];
  } else if (daysPerWeek === 3) {
    scheduleDays = [6, 1, 3]; // Sat, Mon, Wed
  }

  const role = determineRole(r.eid, r.offMail);

  return {
    sl: r.sl,
    eid: r.eid,
    nameEn: r.name,
    designation: r.desig,
    department: r.dept || "Program & Operation",
    project: r.loc || "LEEDO Bangladesh",
    workplace: r.loc || "Head Office, Dhaka",
    status: (r.status === "Active" ? "Active" : "Inactive") as EmploymentStatus,
    role,
    mobileNumber: r.mobile || "N/A",
    personalEmail: r.pMail,
    officialEmail: r.offMail,
    email: r.offMail || r.pMail || `${r.eid}@leedo.org.bd`,
    nid: r.nid,
    dob: r.dob,
    address: r.addr,
    highestEducation: r.edu,
    professionalEducation: r.profEdu,
    fatherOrHusbandName: r.father,
    motherName: r.mother,
    gender: r.gender,
    religion: r.rel,
    natureOfEmployment: (r.nature || "Permanent") as any,
    jobLocationCategory: r.locCat || r.loc,
    jobLocation: r.loc,
    joiningDate: r.doj,
    resignationDate: r.dos,
    lastWorkingDay: r.dos,
    dos: r.dos,
    reasonForDos: r.reason,
    emergencyContact: r.emg,
    remarks: r.remarks,
    reportingSupervisor: r.eid === "1001" ? "Board of Trustees" : "Executive Director",
    employmentType: r.nature || "Permanent",
    
    // Customized Schedule
    workingDaysPerWeek: daysPerWeek,
    workScheduleDays: scheduleDays,
    standardInTime: r.inTime || "09:00 AM",
    standardOutTime: r.outTime || "05:00 PM",
    dailyHours: r.dailyHours || (daysPerWeek === 3 ? 4 : 8),

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
});
